repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: trailing-whitespace
  - hooks:
    - id: black
      language_version: python3
    repo: https://github.com/psf/black
    rev: 21.10b0
  - hooks:
    - id: autoflake
      args:
        - --in-place
    repo: https://github.com/myint/autoflake
    rev: v1.4
  - hooks:
      - id: isort
        language_version: python3
    repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - &flake8
        id: flake8
        additional_dependencies:
          - flake8-docstrings==1.6.0
          - flake8-nb==0.3.0
          - flake8-return==1.1.2
          - flake8-eradicate==1.0.0
          - flake8-no-pep420==1.1.0
        args: ["--config=setup.cfg"]
  - repo: local
    hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
